/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.sagalid.applet;

import java.lang.reflect.InvocationTargetException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ASalasF
 */
public class LindaApplet extends javax.swing.JApplet {

    /**
     * Initializes the applet LindaApplet
     */
    private String rutasParaFirmar;
    private String[] arregloRutasParaFirmar;
    private List<String> listaRutasParaFirmarPDF = new ArrayList<>();
    private List<String> listaRutasParaFirmarXML = new ArrayList<>();

    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LindaApplet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    }
            });
        } catch (InterruptedException | InvocationTargetException ex) {
            System.err.println("Error en la carga del Applet de firma " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setName("Linda"); // NOI18N

        jPasswordField2.setToolTipText("Clave del EToken");

        jButton2.setText("Firmar");
        jButton2.setToolTipText("Presione para firmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 153, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(jPasswordField2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        jPasswordField2.getAccessibleContext().setAccessibleName("JpasswordFieldClaveEToken");
        jButton2.getAccessibleContext().setAccessibleName("jButtonFirmar");
        jLabel1.getAccessibleContext().setAccessibleName("jLabelResultado");
        jLabel1.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        boolean resultadoFirmaPdf = false;
        boolean resultadoFirmaXml = false;


        /*Proceso de obtención de rutas*/
        


        /*Proceso de firma electrónica*/
        AyudanteDeFirma ayudanteDeFirma = new AyudanteDeFirma();
        ayudanteDeFirma.pasoUno_cargaEtoken(new String(jPasswordField2.getPassword()));
        if (ayudanteDeFirma.accesoEtokenLogrado) {
            System.out.println("Archivos a firmar " + getParameter("archivosParaFirmar"));
            ayudanteDeFirma.pasoDos_obtieneRutasParaFirmar(getParameter("archivosParaFirmar"));
            if (ayudanteDeFirma.getCantidadPdfParaFirma() > 0) {
                resultadoFirmaPdf = ayudanteDeFirma.pasoTres_firmaPdf();
            }
            if (ayudanteDeFirma.getCantidadXmlParaFirma() > 0) {
                resultadoFirmaXml = ayudanteDeFirma.pasoCuatro_firmaXml();
            }
            ayudanteDeFirma.pasoCinco_validaFirma();

            if (resultadoFirmaPdf) {
                jLabel1.setText("Firma PDF realizada correctamente!");
            }
            if (resultadoFirmaXml) {
                jLabel1.setText("Firma XML realizada correctamente!");
            }
        } else {
            System.err.println("Error al tratar de acceder al EToken");
            jLabel1.setText("Firma no realizada!");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField2;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the rutasParaFirmar
     */
    public String getRutasParaFirmar() {
        return rutasParaFirmar;
    }

    /**
     * @param rutasParaFirmar the rutasParaFirmar to set
     */
    public void setRutasParaFirmar(String rutasParaFirmar) {
        this.rutasParaFirmar = rutasParaFirmar;
    }

    /**
     * @return the arregloRutasParaFirmar
     */
    public String[] getArregloRutasParaFirmar() {
        return arregloRutasParaFirmar;
    }

    /**
     * @param arregloRutasParaFirmar the arregloRutasParaFirmar to set
     */
    public void setArregloRutasParaFirmar(String[] arregloRutasParaFirmar) {
        this.arregloRutasParaFirmar = arregloRutasParaFirmar;
    }
}
